### ISSUE TITLE
Unable to activate plugin - Module Not Found Error

### ISSUE THREAD

**Issue by Shuffle20** [avaframe/QGisAF#13]
Unable to activate the plugin (with the previous version of AvaFrameConnector it worked correctly)

**Error message:**

Impossibile caricare il plugin 'avaframeConnector' a causa di un errore chiamando il metodo classFactory()

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\avaframeConnector\__init__.py", line 38, in classFactory
    from .avaframeConnector import AvaFrameConnectorPlugin
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\avaframeConnector\avaframeConnector.py", line 38, in 
    from .avaframeConnector_provider import AvaFrameConnectorProvider
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\avaframeConnector\avaframeConnector_provider.py", line 34, in 
    from .avaframeConnector_algorithm import AvaFrameConnectorAlgorithm
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\avaframeConnector\avaframeConnector_algorithm.py", line 70, in 
    import avaframe.version as gv
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'avaframe.version'

**Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.24.0-Tisler Tisler, 6b44a42058**

**Comment by Shuffle20** [comment]
update
i tried with the latest version of Qgis 3.24.2-Tisler.
Same error: ModuleNotFoundError: No module named 'avaframe.version'

**Comment by fso42** [comment]
Uh, hi @Shuffle20 : I am sorry, I somehow missed this issue!
Did you resolve it by now? It looks like you did not update avaframe accordingly. 
Please let me know if you need further assistance. 

Again, I'm sorry about not replying earlier!

**Comment by Shuffle20** [comment]
hi Felix
I have now followed the instructions for the update that you have reported in the matrix room, and I have solved it
thank you very much
